#!/bin/sh

# Checking status

./status_all
./check_slaves
./check_binlogs

echo "min/max/count of id on big_trx of m/s1/s2:"
./m  -te"SELECT MIN(id), MAX(id), COUNT(*) FROM big_trx" test
./s1 -te"SELECT MIN(id), MAX(id), COUNT(*) FROM big_trx" test
./s2 -te"SELECT MIN(id), MAX(id), COUNT(*) FROM big_trx" test

echo "CHECKSUM TABLE of m/s1/s2:"
./m  -te"CHECKSUM TABLE big_trx" test
./s1 -te"CHECKSUM TABLE big_trx" test
./s2 -te"CHECKSUM TABLE big_trx" test
